Fixed bug in header tags
There's an issue where headers won't work properly due to appending a number to a string. 

"h" + 3 results in the following error:
TypeError: cannot concatenate 'str' and 'int' objects